apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-localnet-dev
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
      - name: br-dev
        type: ovs-bridge
        state: up
    ovn:
      bridge-mappings:
        - localnet: localnet-dev
          bridge: br-dev
          state: present
