apiVersion: v1
kind: Namespace
metadata:
  name: vm-demo-1-prod
  labels:
    multinetwork-policy.custom.io/enabled: "true"
  annotations:
    network.custom.io/ingress-ports: "22,443,8443"
    network.custom.io/egress-ports: "22,443,8443"
